// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckActivity() {
  return window['go']['main']['App']['CheckActivity']();
}

export function FindURL(arg1) {
  return window['go']['main']['App']['FindURL'](arg1);
}

export function GetSite(arg1) {
  return window['go']['main']['App']['GetSite'](arg1);
}

export function RemoveStaleActivity(arg1, arg2) {
  return window['go']['main']['App']['RemoveStaleActivity'](arg1, arg2);
}
