// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lib} from '../models';

export function FindURL(arg1:string):Promise<lib.ResponseType>;
