// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckActivity() {
  return window['go']['main']['App']['CheckActivity']();
}

export function FindURL(arg1) {
  return window['go']['main']['App']['FindURL'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSite(arg1) {
  return window['go']['main']['App']['GetSite'](arg1);
}

export function ListGallery() {
  return window['go']['main']['App']['ListGallery']();
}

export function ListGallerySite(arg1) {
  return window['go']['main']['App']['ListGallerySite'](arg1);
}

export function RemoveStaleActivity(arg1, arg2) {
  return window['go']['main']['App']['RemoveStaleActivity'](arg1, arg2);
}

export function ShutdownContentDirWebServer() {
  return window['go']['main']['App']['ShutdownContentDirWebServer']();
}

export function UpdateContentDir() {
  return window['go']['main']['App']['UpdateContentDir']();
}

export function UpdatePortNumber(arg1) {
  return window['go']['main']['App']['UpdatePortNumber'](arg1);
}
